#!/bin/sh
source ./gradle.properties
pipelineName=$GO_PIPELINE_NAME
stageName=$GO_STAGE_NAME
pipelineCounter=$GO_PIPELINE_COUNTER
currentDate=$(date)
status=$2
projectName=$3
notificationBody="
Date :$currentDate
Pipeline Name : $pipelineName
Stage Name : $stageName
Pipeline Counter : $pipelineCounter
Build Status : $status"

echo "Login"
login_url="$app_host/v1/users/login"
echo "URL : $login_url"

login_body='{
    "loginId": "'$app_username'",
    "password": "'$app_password'",
    "workspaceId": "'$app_workspaceId'"
}'

jsessionid=`curl --location --request POST "$login_url" -H 'x-apikey: "'$app_key'"' -H 'Content-Type: application/json' -d "$login_body" | grep -o '"id":"[^"]*"' | cut -c 6- |  tr -d '"'`

echo "JSESSIONID : $jsessionid"

echo "Notification Body: $notificationBody"



url="$app_host/v1/pipelines/notifications?pipelineName=$GO_PIPELINE_NAME&projectName=$projectName&subject=Stage:$GO_PIPELINE_NAME/$GO_PIPELINE_COUNTER/$GO_STAGE_NAME"
echo $url
curl -X POST \
  "$url" \
  -H 'Content-Type: text/html' \
  -H 'JSESSIONID:'$jsessionid'' \
  -d "$notificationBody"